backend:
  name: git-gateway
  branch: main

media_folder: images/photos
public_folder: images/photos

collections:
  - name: "photos"
    label: "Photos"
    folder: "images/photos"
    create: true
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }